spring.application.name=spring-boot-security
spring.jwt.secretkey=Y3lafnYhQA7CFZ8vo9mVCem4a6bLvRe51DKn+hpR3w4=
# Connection URL
spring.datasource.url=jdbc:h2:mem:crudDb

# Hibernate/JPA auto-table creation
spring.jpa.hibernate.ddl-auto=none
